### ISSUE TITLE
feat: Add support for Azure devops

### ISSUE THREAD

**Issue by ieedan** [ieedan/jsrepo#305]
Azure Devops is not currently supported. Going to look into this since I know nothing about it!

_Originally posted by @GiorgioDots in https://github.com/ieedan/jsrepo/discussions/210#discussioncomment-11634441_

**Comment by ieedan** [comment]
Azures URL structure is BY FAR the worst I have seen so this may take longer than expected.

**Comment by ieedan** [comment]
Also DARK MODE ?

**Comment by GiorgioDots** [comment]
> Azures URL structure is BY FAR the worst I have seen so this may take longer than expected.

Yep, I agree, but to add it to jsrepo I thought to change it with something like "{org_name}.azuredevops.com/{project_name}/{repo_name}" and parse this string to get the mandatory params when fetching raw files. Could this be a good solution?

**Comment by GiorgioDots** [comment]
> Also DARK MODE ?
It does have dark mode, you can change theme from the [user preferences page](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/set-your-preferences?view=azure-devops&tabs=current-page)

**Comment by ieedan** [comment]
You can see what I have at https://github.com/ieedan/jsrepo/tree/azure-dev-ops

My goal with jsrepo has always been so that you can paste the URL from the homepage of your repo and it should just work. That way you don't have to know or learn anything about each provider.

In this case the url looks like this on the homepage:
```
https://dev.azure.com/aidanbleser/_git/std?path=/&version=GTv1.6.0&_a=contents
```

**Comment by ieedan** [comment]
The problem I am currently having is that from that URL as far as I can tell there is no way of knowing the project name.

**Comment by ieedan** [comment]
@GiorgioDots any way I do this parsing for the URLs is going to need a complete overhaul, things are gonna have to be smarter than they are at the moment.

What do you think is the most intuitive way to make it so that the project name is also in the URL? A query parameter something else?

Unfortunately the current URL structure doesn't make it possible to determine the project name just from the URL alone.

**Comment by ieedan** [comment]
Maybe azure just will be a completely custom URL because of this so I would make it something like:
```
azure/<org>/<project>/<repo>/(heads|tags)/<ref>
```

We would just have to ditch the copy paste goal for this provider since they are difficult.

**Comment by GiorgioDots** [comment]
> @GiorgioDots any way I do this parsing for the URLs is going to need a complete overhaul, things are gonna have to be smarter than they are at the moment.
> 
> What do you think is the most intuitive way to make it so that the project name is also in the URL? A query parameter something else?
> 
> Unfortunately the current URL structure doesn't make it possible to determine the project name just from the URL alone.

Yes, unfortunately it' a little tricky how it works.
There are 3 possible urls:
- The old one (changed in 2018 to the new one but still active): `<org>.visualstudio.com/<project>/_git/<repo>`
- The new one: `dev.azure.com/<org>/<project>/_git/<repo>`
- For both old and new urls, if there is only one repo in the project, the project name and the repo name are in the same spot inside the url. For example, from `dev.azure.com/aidanbleser/_git/std` i could tell that `std` is the project name and the repo name. It will change to `dev.azure.com/aidanbleser/std/_git/std` when you add a new repo inside the project

So, there are two solutions:
- one a little tricky, but will be compatible with your goal, which is to handle those three cases and retrieve the information based on the url structure. But i can't find a way to handle branches and tags, so it will not be be fully compatible.
- The second one is the one you mentioned: 

> Maybe azure just will be a completely custom URL because of this so I would make it something like:
> 
> ```
> azure/<org>/<project>/<repo>/(heads|tags)/<ref>
> ```
> 
> We would just have to ditch the copy paste goal for this provider since they are difficult.
> 
> Let me know what you think!

Unfortunately it won't fit with the copy paste goal (which i really like), but it can handle all the cases with one url structure.


For both solutions, i found that it's possible to fetch the raw contents through [this api](https://learn.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-file-contents?view=azure-devops-rest-7.1). With this request it's possible to handle the private repos too by adding an `Authentication: Basic {token}` header. The token can be added with the current jsrepo flow, the user just needs to add a [Personal Access Token](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&view=azure-devops&tabs=Windows), The only note is that the token needs to be encoded to UTF8 byte[] and converted to a base64 string before being added to the header, [here's the docs](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&view=azure-devops&tabs=Windows#use-a-pat)


Even if it doesn't fit with your goal of copy and paste, I personally prefer the second solution, because it handles branches and tags too, it also clears the unnecessarily complex urls.

**Comment by ieedan** [comment]
> > @GiorgioDots any way I do this parsing for the URLs is going to need a complete overhaul, things are gonna have to be smarter than they are at the moment.
> 
> > 
> 
> > What do you think is the most intuitive way to make it so that the project name is also in the URL? A query parameter something else?
> 
> > 
> 
> > Unfortunately the current URL structure doesn't make it possible to determine the project name just from the URL alone.
> 
> 
> 
> Yes, unfortunately it' a little tricky how it works.
> 
> There are 3 possible urls:
> 
> - The old one (changed in 2018 to the new one but still active): `<org>.visualstudio.com/<project>/_git/<repo>`
> 
> - The new one: `dev.azure.com/<org>/<project>/_git/<repo>`
> 
> - For both old and new urls, if there is only one repo in the project, the project name and the repo name are in the same spot inside the url. For example, from `dev.azure.com/aidanbleser/_git/std` i could tell that `std` is the project name and the repo name. It will change to `dev.azure.com/aidanbleser/std/_git/std` when you add a new repo inside the project
> 
> 
> 
> So, there are two solutions:
> 
> - one a little tricky, but will be compatible with your goal, which is to handle those three cases and retrieve the information based on the url structure. But i can't find a way to handle branches and tags, so it will not be be fully compatible.
> 
> - The second one is the one you mentioned: 
> 
> 
> 
> > Maybe azure just will be a completely custom URL because of this so I would make it something like:
> 
> > 
> 
> > ```
> 
> > azure/<org>/<project>/<repo>/(heads|tags)/<ref>
> 
> > ```
> 
> > 
> 
> > We would just have to ditch the copy paste goal for this provider since they are difficult.
> 
> > 
> 
> > Let me know what you think!
> 
> 
> 
> Unfortunately it won't fit with the copy paste goal (which i really like), but it can handle all the cases with one url structure.
> 
> 
> 
> 
> 
> For both solutions, i found that it's possible to fetch the raw contents through [this api](https://learn.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-file-contents?view=azure-devops-rest-7.1). With this request it's possible to handle the private repos too by adding an `Authentication: Basic {token}` header. The token can be added with the current jsrepo flow, the user just needs to add a [Personal Access Token](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&view=azure-devops&tabs=Windows), The only note is that the token needs to be encoded to UTF8 byte[] and converted to a base64 string before being added to the header, [here's the docs](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&view=azure-devops&tabs=Windows#use-a-pat)
> 
> 
> 
> 
> 
> Even if it doesn't fit with your goal of copy and paste, I personally prefer the second solution, because it handles branches and tags too, it also clears the unnecessarily complex urls. 

From my testing it's Bearer scheme for private repos.

Unfortunately even my solution with the custom URL has its own shortcomings like I still need to implement more custom parsing to handle urls that aren't just 3 segments for fully qualified adds.

I'll have to think about it a bit more ig.

**Comment by ieedan** [comment]
Are there any plans to deprecate the 2018 URL structure? And whats the easiest way for users to find that?

**Comment by ieedan** [comment]
I think I am going to go with my earlier proposed URL structure. And we will just document how it should be used and why it has to be that way.

I am still going to need to update parsing for fully qualified adds to support a longer URL since it's pretty fragile at the moment.

**Comment by GiorgioDots** [comment]
> Are there any plans to deprecate the 2018 URL structure? And whats the easiest way for users to find that?

I can't find any information about this, so i think it will be active for a long time.
With "whats the easiest way for users to find that?", what do you mean?

**Comment by GiorgioDots** [comment]
> I think I am going to go with my earlier proposed URL structure. And we will just document how it should be used and why it has to be that way.
> 
> I am still going to need to update parsing for fully qualified adds to support a longer URL since it's pretty fragile at the moment.

Ok, it's a good workaround in my opinion.

**Comment by GiorgioDots** [comment]
@ieedan about azure's authenticated repositories, where did you find that the requests works with Bearer auth too? I can't find anything about it. It works by passing a Personal Access Token too, so that's great!

**Comment by ieedan** [comment]
> @ieedan about azure's authenticated repositories, where did you find that the requests works with Bearer auth too? I can't find anything about it. It works by passing a Personal Access Token too, so that's great!

I tried basic as that's what I saw as well but it didn't work so I tried bearer
